/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardTranslateRouteImport } from './routes/dashboard/translate'
import { Route as DashboardPlansRouteImport } from './routes/dashboard/plans'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardUsersIndexRouteImport } from './routes/admin/dashboard/users/index'
import { Route as AdminDashboardOrganizationsIndexRouteImport } from './routes/admin/dashboard/organizations/index'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTranslateRoute = DashboardTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansRoute = DashboardPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardUsersIndexRoute =
  AdminDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardOrganizationsIndexRoute =
  AdminDashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/translate': typeof DashboardTranslateRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/organizations': typeof AdminDashboardOrganizationsIndexRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/translate': typeof DashboardTranslateRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/dashboard/organizations': typeof AdminDashboardOrganizationsIndexRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/translate': typeof DashboardTranslateRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/organizations/': typeof AdminDashboardOrganizationsIndexRoute
  '/admin/dashboard/users/': typeof AdminDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/register'
    | '/setup'
    | '/admin/dashboard'
    | '/dashboard/plans'
    | '/dashboard/translate'
    | '/admin'
    | '/dashboard/'
    | '/admin/dashboard/'
    | '/admin/dashboard/organizations'
    | '/admin/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/setup'
    | '/dashboard/plans'
    | '/dashboard/translate'
    | '/admin'
    | '/dashboard'
    | '/admin/dashboard'
    | '/admin/dashboard/organizations'
    | '/admin/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/register'
    | '/setup'
    | '/admin/dashboard'
    | '/dashboard/plans'
    | '/dashboard/translate'
    | '/admin/'
    | '/dashboard/'
    | '/admin/dashboard/'
    | '/admin/dashboard/organizations/'
    | '/admin/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/translate': {
      id: '/dashboard/translate'
      path: '/translate'
      fullPath: '/dashboard/translate'
      preLoaderRoute: typeof DashboardTranslateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plans': {
      id: '/dashboard/plans'
      path: '/plans'
      fullPath: '/dashboard/plans'
      preLoaderRoute: typeof DashboardPlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/users/': {
      id: '/admin/dashboard/users/'
      path: '/users'
      fullPath: '/admin/dashboard/users'
      preLoaderRoute: typeof AdminDashboardUsersIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/organizations/': {
      id: '/admin/dashboard/organizations/'
      path: '/organizations'
      fullPath: '/admin/dashboard/organizations'
      preLoaderRoute: typeof AdminDashboardOrganizationsIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardPlansRoute: typeof DashboardPlansRoute
  DashboardTranslateRoute: typeof DashboardTranslateRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPlansRoute: DashboardPlansRoute,
  DashboardTranslateRoute: DashboardTranslateRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AdminDashboardRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardOrganizationsIndexRoute: typeof AdminDashboardOrganizationsIndexRoute
  AdminDashboardUsersIndexRoute: typeof AdminDashboardUsersIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardOrganizationsIndexRoute: AdminDashboardOrganizationsIndexRoute,
  AdminDashboardUsersIndexRoute: AdminDashboardUsersIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
